"""initial_casino_and_idempotency_tables

Revision ID: 8a34c3f94b87
Revises:
Create Date: 2026-08-14 16:21:37.167845

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a34c3f94b87"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casino_players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identity_user_id", sa.UUID(), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_casino_players_identity_user_id"),
        "casino_players",
        ["identity_user_id"],
        unique=True,
    )
    op.create_table(
        "casino_rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "game_type",
            sa.Enum("dice_duel", "crash", "roulette", name="gametype", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("public", "private", name="roomvisibility", native_enum=False),
            nullable=False,
        ),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("owner_player_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "closed", "archived", name="roomstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("invite_token_hash", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "\n            (is_system = TRUE AND owner_player_id IS NULL)\n            OR\n            (is_system = FALSE AND owner_player_id IS NOT NULL)\n            ",
            name="check_casino_rooms_system_owner_policy",
        ),
        sa.CheckConstraint("capacity > 0", name="check_casino_rooms_capacity_positive"),
        sa.CheckConstraint("revision >= 1", name="check_casino_rooms_revision_min"),
        sa.ForeignKeyConstraint(["owner_player_id"], ["casino_players.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_casino_rooms_game_type"), "casino_rooms", ["game_type"], unique=False)
    op.create_index(
        op.f("ix_casino_rooms_owner_player_id"), "casino_rooms", ["owner_player_id"], unique=False
    )
    op.create_index(op.f("ix_casino_rooms_status"), "casino_rooms", ["status"], unique=False)
    op.create_index(
        "ix_casino_rooms_status_visibility_game_type",
        "casino_rooms",
        ["status", "visibility", "game_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_casino_rooms_visibility"), "casino_rooms", ["visibility"], unique=False
    )
    op.create_table(
        "casino_room_participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("seat", sa.Integer(), nullable=False),
        sa.Column(
            "membership_status",
            sa.Enum("active", "left", name="membershipstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "connection_status",
            sa.Enum("connected", "disconnected", name="connectionstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconnect_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("seat >= 1", name="check_casino_room_participants_seat_min"),
        sa.ForeignKeyConstraint(["player_id"], ["casino_players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_id"], ["casino_rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_casino_room_participants_membership_status"),
        "casino_room_participants",
        ["membership_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_casino_room_participants_player_id"),
        "casino_room_participants",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_casino_room_participants_room_id"),
        "casino_room_participants",
        ["room_id"],
        unique=False,
    )
    op.create_index(
        "uq_casino_room_participants_active_room_player",
        "casino_room_participants",
        ["room_id", "player_id"],
        unique=True,
        postgresql_where=sa.text("membership_status = 'active'"),
    )
    op.create_index(
        "uq_casino_room_participants_active_room_seat",
        "casino_room_participants",
        ["room_id", "seat"],
        unique=True,
        postgresql_where=sa.text("membership_status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_casino_room_participants_active_room_seat",
        table_name="casino_room_participants",
        postgresql_where=sa.text("membership_status = 'active'"),
    )
    op.drop_index(
        "uq_casino_room_participants_active_room_player",
        table_name="casino_room_participants",
        postgresql_where=sa.text("membership_status = 'active'"),
    )
    op.drop_index(
        op.f("ix_casino_room_participants_room_id"), table_name="casino_room_participants"
    )
    op.drop_index(
        op.f("ix_casino_room_participants_player_id"), table_name="casino_room_participants"
    )
    op.drop_index(
        op.f("ix_casino_room_participants_membership_status"), table_name="casino_room_participants"
    )
    op.drop_table("casino_room_participants")
    op.drop_index(op.f("ix_casino_rooms_visibility"), table_name="casino_rooms")
    op.drop_index("ix_casino_rooms_status_visibility_game_type", table_name="casino_rooms")
    op.drop_index(op.f("ix_casino_rooms_status"), table_name="casino_rooms")
    op.drop_index(op.f("ix_casino_rooms_owner_player_id"), table_name="casino_rooms")
    op.drop_index(op.f("ix_casino_rooms_game_type"), table_name="casino_rooms")
    op.drop_table("casino_rooms")
    op.drop_index(op.f("ix_casino_players_identity_user_id"), table_name="casino_players")
    op.drop_table("casino_players")
    # ### end Alembic commands ###
