# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from wallet.v1 import wallet_service_pb2 as wallet_dot_v1_dot_wallet__service__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in wallet/v1/wallet_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class WalletServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWallet = channel.unary_unary(
            "/wallet.v1.WalletService/GetWallet",
            request_serializer=wallet_dot_v1_dot_wallet__service__pb2.GetWalletRequest.SerializeToString,
            response_deserializer=wallet_dot_v1_dot_wallet__service__pb2.GetWalletResponse.FromString,
            _registered_method=True,
        )
        self.ListLedgerEntries = channel.unary_unary(
            "/wallet.v1.WalletService/ListLedgerEntries",
            request_serializer=wallet_dot_v1_dot_wallet__service__pb2.ListLedgerEntriesRequest.SerializeToString,
            response_deserializer=wallet_dot_v1_dot_wallet__service__pb2.ListLedgerEntriesResponse.FromString,
            _registered_method=True,
        )
        self.ReserveFunds = channel.unary_unary(
            "/wallet.v1.WalletService/ReserveFunds",
            request_serializer=wallet_dot_v1_dot_wallet__service__pb2.ReserveFundsRequest.SerializeToString,
            response_deserializer=wallet_dot_v1_dot_wallet__service__pb2.ReserveFundsResponse.FromString,
            _registered_method=True,
        )
        self.SettleBet = channel.unary_unary(
            "/wallet.v1.WalletService/SettleBet",
            request_serializer=wallet_dot_v1_dot_wallet__service__pb2.SettleBetRequest.SerializeToString,
            response_deserializer=wallet_dot_v1_dot_wallet__service__pb2.SettleBetResponse.FromString,
            _registered_method=True,
        )
        self.ReleaseReservation = channel.unary_unary(
            "/wallet.v1.WalletService/ReleaseReservation",
            request_serializer=wallet_dot_v1_dot_wallet__service__pb2.ReleaseReservationRequest.SerializeToString,
            response_deserializer=wallet_dot_v1_dot_wallet__service__pb2.ReleaseReservationResponse.FromString,
            _registered_method=True,
        )
        self.CreditReward = channel.unary_unary(
            "/wallet.v1.WalletService/CreditReward",
            request_serializer=wallet_dot_v1_dot_wallet__service__pb2.CreditRewardRequest.SerializeToString,
            response_deserializer=wallet_dot_v1_dot_wallet__service__pb2.CreditRewardResponse.FromString,
            _registered_method=True,
        )
        self.AdjustBalance = channel.unary_unary(
            "/wallet.v1.WalletService/AdjustBalance",
            request_serializer=wallet_dot_v1_dot_wallet__service__pb2.AdjustBalanceRequest.SerializeToString,
            response_deserializer=wallet_dot_v1_dot_wallet__service__pb2.AdjustBalanceResponse.FromString,
            _registered_method=True,
        )


class WalletServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListLedgerEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReserveFunds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SettleBet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReleaseReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreditReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AdjustBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetWallet": grpc.unary_unary_rpc_method_handler(
            servicer.GetWallet,
            request_deserializer=wallet_dot_v1_dot_wallet__service__pb2.GetWalletRequest.FromString,
            response_serializer=wallet_dot_v1_dot_wallet__service__pb2.GetWalletResponse.SerializeToString,
        ),
        "ListLedgerEntries": grpc.unary_unary_rpc_method_handler(
            servicer.ListLedgerEntries,
            request_deserializer=wallet_dot_v1_dot_wallet__service__pb2.ListLedgerEntriesRequest.FromString,
            response_serializer=wallet_dot_v1_dot_wallet__service__pb2.ListLedgerEntriesResponse.SerializeToString,
        ),
        "ReserveFunds": grpc.unary_unary_rpc_method_handler(
            servicer.ReserveFunds,
            request_deserializer=wallet_dot_v1_dot_wallet__service__pb2.ReserveFundsRequest.FromString,
            response_serializer=wallet_dot_v1_dot_wallet__service__pb2.ReserveFundsResponse.SerializeToString,
        ),
        "SettleBet": grpc.unary_unary_rpc_method_handler(
            servicer.SettleBet,
            request_deserializer=wallet_dot_v1_dot_wallet__service__pb2.SettleBetRequest.FromString,
            response_serializer=wallet_dot_v1_dot_wallet__service__pb2.SettleBetResponse.SerializeToString,
        ),
        "ReleaseReservation": grpc.unary_unary_rpc_method_handler(
            servicer.ReleaseReservation,
            request_deserializer=wallet_dot_v1_dot_wallet__service__pb2.ReleaseReservationRequest.FromString,
            response_serializer=wallet_dot_v1_dot_wallet__service__pb2.ReleaseReservationResponse.SerializeToString,
        ),
        "CreditReward": grpc.unary_unary_rpc_method_handler(
            servicer.CreditReward,
            request_deserializer=wallet_dot_v1_dot_wallet__service__pb2.CreditRewardRequest.FromString,
            response_serializer=wallet_dot_v1_dot_wallet__service__pb2.CreditRewardResponse.SerializeToString,
        ),
        "AdjustBalance": grpc.unary_unary_rpc_method_handler(
            servicer.AdjustBalance,
            request_deserializer=wallet_dot_v1_dot_wallet__service__pb2.AdjustBalanceRequest.FromString,
            response_serializer=wallet_dot_v1_dot_wallet__service__pb2.AdjustBalanceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "wallet.v1.WalletService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "wallet.v1.WalletService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class WalletService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWallet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.v1.WalletService/GetWallet",
            wallet_dot_v1_dot_wallet__service__pb2.GetWalletRequest.SerializeToString,
            wallet_dot_v1_dot_wallet__service__pb2.GetWalletResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListLedgerEntries(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.v1.WalletService/ListLedgerEntries",
            wallet_dot_v1_dot_wallet__service__pb2.ListLedgerEntriesRequest.SerializeToString,
            wallet_dot_v1_dot_wallet__service__pb2.ListLedgerEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReserveFunds(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.v1.WalletService/ReserveFunds",
            wallet_dot_v1_dot_wallet__service__pb2.ReserveFundsRequest.SerializeToString,
            wallet_dot_v1_dot_wallet__service__pb2.ReserveFundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SettleBet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.v1.WalletService/SettleBet",
            wallet_dot_v1_dot_wallet__service__pb2.SettleBetRequest.SerializeToString,
            wallet_dot_v1_dot_wallet__service__pb2.SettleBetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReleaseReservation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.v1.WalletService/ReleaseReservation",
            wallet_dot_v1_dot_wallet__service__pb2.ReleaseReservationRequest.SerializeToString,
            wallet_dot_v1_dot_wallet__service__pb2.ReleaseReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreditReward(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.v1.WalletService/CreditReward",
            wallet_dot_v1_dot_wallet__service__pb2.CreditRewardRequest.SerializeToString,
            wallet_dot_v1_dot_wallet__service__pb2.CreditRewardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AdjustBalance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wallet.v1.WalletService/AdjustBalance",
            wallet_dot_v1_dot_wallet__service__pb2.AdjustBalanceRequest.SerializeToString,
            wallet_dot_v1_dot_wallet__service__pb2.AdjustBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
