# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from identity.v1 import (
    identity_service_pb2 as identity_dot_v1_dot_identity__service__pb2,
)

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in identity/v1/identity_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class IdentityServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
            "/identity.v1.IdentityService/Register",
            request_serializer=identity_dot_v1_dot_identity__service__pb2.RegisterRequest.SerializeToString,
            response_deserializer=identity_dot_v1_dot_identity__service__pb2.RegisterResponse.FromString,
            _registered_method=True,
        )
        self.Login = channel.unary_unary(
            "/identity.v1.IdentityService/Login",
            request_serializer=identity_dot_v1_dot_identity__service__pb2.LoginRequest.SerializeToString,
            response_deserializer=identity_dot_v1_dot_identity__service__pb2.LoginResponse.FromString,
            _registered_method=True,
        )
        self.RefreshToken = channel.unary_unary(
            "/identity.v1.IdentityService/RefreshToken",
            request_serializer=identity_dot_v1_dot_identity__service__pb2.RefreshTokenRequest.SerializeToString,
            response_deserializer=identity_dot_v1_dot_identity__service__pb2.RefreshTokenResponse.FromString,
            _registered_method=True,
        )
        self.Logout = channel.unary_unary(
            "/identity.v1.IdentityService/Logout",
            request_serializer=identity_dot_v1_dot_identity__service__pb2.LogoutRequest.SerializeToString,
            response_deserializer=identity_dot_v1_dot_identity__service__pb2.LogoutResponse.FromString,
            _registered_method=True,
        )
        self.GetMe = channel.unary_unary(
            "/identity.v1.IdentityService/GetMe",
            request_serializer=identity_dot_v1_dot_identity__service__pb2.GetMeRequest.SerializeToString,
            response_deserializer=identity_dot_v1_dot_identity__service__pb2.GetMeResponse.FromString,
            _registered_method=True,
        )
        self.GetUser = channel.unary_unary(
            "/identity.v1.IdentityService/GetUser",
            request_serializer=identity_dot_v1_dot_identity__service__pb2.GetUserRequest.SerializeToString,
            response_deserializer=identity_dot_v1_dot_identity__service__pb2.GetUserResponse.FromString,
            _registered_method=True,
        )
        self.ListUsers = channel.unary_unary(
            "/identity.v1.IdentityService/ListUsers",
            request_serializer=identity_dot_v1_dot_identity__service__pb2.ListUsersRequest.SerializeToString,
            response_deserializer=identity_dot_v1_dot_identity__service__pb2.ListUsersResponse.FromString,
            _registered_method=True,
        )
        self.BlockUser = channel.unary_unary(
            "/identity.v1.IdentityService/BlockUser",
            request_serializer=identity_dot_v1_dot_identity__service__pb2.BlockUserRequest.SerializeToString,
            response_deserializer=identity_dot_v1_dot_identity__service__pb2.BlockUserResponse.FromString,
            _registered_method=True,
        )


class IdentityServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BlockUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Register": grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=identity_dot_v1_dot_identity__service__pb2.RegisterRequest.FromString,
            response_serializer=identity_dot_v1_dot_identity__service__pb2.RegisterResponse.SerializeToString,
        ),
        "Login": grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=identity_dot_v1_dot_identity__service__pb2.LoginRequest.FromString,
            response_serializer=identity_dot_v1_dot_identity__service__pb2.LoginResponse.SerializeToString,
        ),
        "RefreshToken": grpc.unary_unary_rpc_method_handler(
            servicer.RefreshToken,
            request_deserializer=identity_dot_v1_dot_identity__service__pb2.RefreshTokenRequest.FromString,
            response_serializer=identity_dot_v1_dot_identity__service__pb2.RefreshTokenResponse.SerializeToString,
        ),
        "Logout": grpc.unary_unary_rpc_method_handler(
            servicer.Logout,
            request_deserializer=identity_dot_v1_dot_identity__service__pb2.LogoutRequest.FromString,
            response_serializer=identity_dot_v1_dot_identity__service__pb2.LogoutResponse.SerializeToString,
        ),
        "GetMe": grpc.unary_unary_rpc_method_handler(
            servicer.GetMe,
            request_deserializer=identity_dot_v1_dot_identity__service__pb2.GetMeRequest.FromString,
            response_serializer=identity_dot_v1_dot_identity__service__pb2.GetMeResponse.SerializeToString,
        ),
        "GetUser": grpc.unary_unary_rpc_method_handler(
            servicer.GetUser,
            request_deserializer=identity_dot_v1_dot_identity__service__pb2.GetUserRequest.FromString,
            response_serializer=identity_dot_v1_dot_identity__service__pb2.GetUserResponse.SerializeToString,
        ),
        "ListUsers": grpc.unary_unary_rpc_method_handler(
            servicer.ListUsers,
            request_deserializer=identity_dot_v1_dot_identity__service__pb2.ListUsersRequest.FromString,
            response_serializer=identity_dot_v1_dot_identity__service__pb2.ListUsersResponse.SerializeToString,
        ),
        "BlockUser": grpc.unary_unary_rpc_method_handler(
            servicer.BlockUser,
            request_deserializer=identity_dot_v1_dot_identity__service__pb2.BlockUserRequest.FromString,
            response_serializer=identity_dot_v1_dot_identity__service__pb2.BlockUserResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "identity.v1.IdentityService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "identity.v1.IdentityService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class IdentityService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/identity.v1.IdentityService/Register",
            identity_dot_v1_dot_identity__service__pb2.RegisterRequest.SerializeToString,
            identity_dot_v1_dot_identity__service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Login(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/identity.v1.IdentityService/Login",
            identity_dot_v1_dot_identity__service__pb2.LoginRequest.SerializeToString,
            identity_dot_v1_dot_identity__service__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RefreshToken(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/identity.v1.IdentityService/RefreshToken",
            identity_dot_v1_dot_identity__service__pb2.RefreshTokenRequest.SerializeToString,
            identity_dot_v1_dot_identity__service__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Logout(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/identity.v1.IdentityService/Logout",
            identity_dot_v1_dot_identity__service__pb2.LogoutRequest.SerializeToString,
            identity_dot_v1_dot_identity__service__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/identity.v1.IdentityService/GetMe",
            identity_dot_v1_dot_identity__service__pb2.GetMeRequest.SerializeToString,
            identity_dot_v1_dot_identity__service__pb2.GetMeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/identity.v1.IdentityService/GetUser",
            identity_dot_v1_dot_identity__service__pb2.GetUserRequest.SerializeToString,
            identity_dot_v1_dot_identity__service__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListUsers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/identity.v1.IdentityService/ListUsers",
            identity_dot_v1_dot_identity__service__pb2.ListUsersRequest.SerializeToString,
            identity_dot_v1_dot_identity__service__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BlockUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/identity.v1.IdentityService/BlockUser",
            identity_dot_v1_dot_identity__service__pb2.BlockUserRequest.SerializeToString,
            identity_dot_v1_dot_identity__service__pb2.BlockUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
