import type { RoomSummaryDto } from './types';

export const mockRooms: RoomSummaryDto[] = [
  {
    id: 'room-1',
    name: 'Crash VIP',
    game_type: 'crash',
    visibility: 'public',
    status: 'open',
    participants_count: 45,
    capacity: 100,
    min_bet: 10,
    max_bet: 1000,
    created_at: '2026-08-21T10:00:00Z',
  },
  {
    id: 'room-2',
    name: 'Roulette Classic',
    game_type: 'roulette',
    visibility: 'public',
    status: 'open',
    participants_count: 12,
    capacity: 50,
    min_bet: 5,
    max_bet: 500,
    created_at: '2026-08-21T09:30:00Z',
  },
  {
    id: 'room-3',
    name: 'Dice Duel Pro',
    game_type: 'dice_duel',
    visibility: 'public',
    status: 'closed',
    participants_count: 0,
    capacity: 30,
    min_bet: 20,
    max_bet: 2000,
    created_at: '2026-08-21T08:00:00Z',
  },
  {
    id: 'room-4',
    name: 'Private Crash',
    game_type: 'crash',
    visibility: 'private',
    status: 'open',
    participants_count: 8,
    capacity: 20,
    min_bet: 50,
    max_bet: 5000,
    created_at: '2026-08-21T11:00:00Z',
  },
  {
    id: 'room-5',
    name: 'Roulette Tournament',
    game_type: 'roulette',
    visibility: 'public',
    status: 'in_progress',
    participants_count: 48,
    capacity: 50,
    min_bet: 100,
    max_bet: 10000,
    created_at: '2026-08-21T07:00:00Z',
  },
  {
    id: 'room-6',
    name: 'Private Dice Club',
    game_type: 'dice_duel',
    visibility: 'private',
    status: 'closed',
    participants_count: 0,
    capacity: 15,
    min_bet: 1000,
    max_bet: 50000,
    created_at: '2026-08-21T06:00:00Z',
  },
];