# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from casino.v1 import bet_service_pb2 as casino_dot_v1_dot_bet__service__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in casino/v1/bet_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CasinoBetServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceBet = channel.unary_unary(
            "/casino.v1.CasinoBetService/PlaceBet",
            request_serializer=casino_dot_v1_dot_bet__service__pb2.PlaceBetRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_bet__service__pb2.PlaceBetResponse.FromString,
            _registered_method=True,
        )
        self.CancelBet = channel.unary_unary(
            "/casino.v1.CasinoBetService/CancelBet",
            request_serializer=casino_dot_v1_dot_bet__service__pb2.CancelBetRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_bet__service__pb2.CancelBetResponse.FromString,
            _registered_method=True,
        )
        self.GetBet = channel.unary_unary(
            "/casino.v1.CasinoBetService/GetBet",
            request_serializer=casino_dot_v1_dot_bet__service__pb2.GetBetRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_bet__service__pb2.GetBetResponse.FromString,
            _registered_method=True,
        )
        self.ListMyBets = channel.unary_unary(
            "/casino.v1.CasinoBetService/ListMyBets",
            request_serializer=casino_dot_v1_dot_bet__service__pb2.ListMyBetsRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_bet__service__pb2.ListMyBetsResponse.FromString,
            _registered_method=True,
        )


class CasinoBetServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PlaceBet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelBet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetBet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMyBets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CasinoBetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "PlaceBet": grpc.unary_unary_rpc_method_handler(
            servicer.PlaceBet,
            request_deserializer=casino_dot_v1_dot_bet__service__pb2.PlaceBetRequest.FromString,
            response_serializer=casino_dot_v1_dot_bet__service__pb2.PlaceBetResponse.SerializeToString,
        ),
        "CancelBet": grpc.unary_unary_rpc_method_handler(
            servicer.CancelBet,
            request_deserializer=casino_dot_v1_dot_bet__service__pb2.CancelBetRequest.FromString,
            response_serializer=casino_dot_v1_dot_bet__service__pb2.CancelBetResponse.SerializeToString,
        ),
        "GetBet": grpc.unary_unary_rpc_method_handler(
            servicer.GetBet,
            request_deserializer=casino_dot_v1_dot_bet__service__pb2.GetBetRequest.FromString,
            response_serializer=casino_dot_v1_dot_bet__service__pb2.GetBetResponse.SerializeToString,
        ),
        "ListMyBets": grpc.unary_unary_rpc_method_handler(
            servicer.ListMyBets,
            request_deserializer=casino_dot_v1_dot_bet__service__pb2.ListMyBetsRequest.FromString,
            response_serializer=casino_dot_v1_dot_bet__service__pb2.ListMyBetsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "casino.v1.CasinoBetService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "casino.v1.CasinoBetService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CasinoBetService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlaceBet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoBetService/PlaceBet",
            casino_dot_v1_dot_bet__service__pb2.PlaceBetRequest.SerializeToString,
            casino_dot_v1_dot_bet__service__pb2.PlaceBetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelBet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoBetService/CancelBet",
            casino_dot_v1_dot_bet__service__pb2.CancelBetRequest.SerializeToString,
            casino_dot_v1_dot_bet__service__pb2.CancelBetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetBet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoBetService/GetBet",
            casino_dot_v1_dot_bet__service__pb2.GetBetRequest.SerializeToString,
            casino_dot_v1_dot_bet__service__pb2.GetBetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListMyBets(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoBetService/ListMyBets",
            casino_dot_v1_dot_bet__service__pb2.ListMyBetsRequest.SerializeToString,
            casino_dot_v1_dot_bet__service__pb2.ListMyBetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
