# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: casino/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "casino/v1/common.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16\x63\x61sino/v1/common.proto\x12\tcasino.v1\x1a\x1fgoogle/protobuf/timestamp.proto"Y\n\x0eRequestContext\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x1e\n\x16\x61\x63tor_identity_user_id\x18\x02 \x01(\t\x12\x13\n\x0bpermissions\x18\x03 \x03(\t"/\n\x05Money\x12\x14\n\x0c\x61mount_minor\x18\x01 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t"\xed\x01\n\x13\x43\x61sinoPlayerSummary\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x18\n\x10identity_user_id\x18\x02 \x01(\t\x12\x15\n\x08nickname\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x17\n\navatar_url\x18\x04 \x01(\tH\x01\x88\x01\x01\x12-\n\x06status\x18\x05 \x01(\x0e\x32\x1d.casino.v1.CasinoPlayerStatus\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0b\n\t_nicknameB\r\n\x0b_avatar_url*k\n\x08GameType\x12\x19\n\x15GAME_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13GAME_TYPE_DICE_DUEL\x10\x01\x12\x13\n\x0fGAME_TYPE_CRASH\x10\x02\x12\x16\n\x12GAME_TYPE_ROULETTE\x10\x03*}\n\x12\x43\x61sinoPlayerStatus\x12$\n CASINO_PLAYER_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x43\x41SINO_PLAYER_STATUS_ACTIVE\x10\x01\x12 \n\x1c\x43\x41SINO_PLAYER_STATUS_BLOCKED\x10\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "casino.v1.common_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GAMETYPE"]._serialized_start = 450
    _globals["_GAMETYPE"]._serialized_end = 557
    _globals["_CASINOPLAYERSTATUS"]._serialized_start = 559
    _globals["_CASINOPLAYERSTATUS"]._serialized_end = 684
    _globals["_REQUESTCONTEXT"]._serialized_start = 70
    _globals["_REQUESTCONTEXT"]._serialized_end = 159
    _globals["_MONEY"]._serialized_start = 161
    _globals["_MONEY"]._serialized_end = 208
    _globals["_CASINOPLAYERSUMMARY"]._serialized_start = 211
    _globals["_CASINOPLAYERSUMMARY"]._serialized_end = 448
# @@protoc_insertion_point(module_scope)
