# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from casino.v1 import room_service_pb2 as casino_dot_v1_dot_room__service__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in casino/v1/room_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CasinoRoomServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRoom = channel.unary_unary(
            "/casino.v1.CasinoRoomService/CreateRoom",
            request_serializer=casino_dot_v1_dot_room__service__pb2.CreateRoomRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_room__service__pb2.CreateRoomResponse.FromString,
            _registered_method=True,
        )
        self.ListRooms = channel.unary_unary(
            "/casino.v1.CasinoRoomService/ListRooms",
            request_serializer=casino_dot_v1_dot_room__service__pb2.ListRoomsRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_room__service__pb2.ListRoomsResponse.FromString,
            _registered_method=True,
        )
        self.GetRoomSnapshot = channel.unary_unary(
            "/casino.v1.CasinoRoomService/GetRoomSnapshot",
            request_serializer=casino_dot_v1_dot_room__service__pb2.GetRoomSnapshotRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_room__service__pb2.GetRoomSnapshotResponse.FromString,
            _registered_method=True,
        )
        self.JoinRoom = channel.unary_unary(
            "/casino.v1.CasinoRoomService/JoinRoom",
            request_serializer=casino_dot_v1_dot_room__service__pb2.JoinRoomRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_room__service__pb2.JoinRoomResponse.FromString,
            _registered_method=True,
        )
        self.LeaveRoom = channel.unary_unary(
            "/casino.v1.CasinoRoomService/LeaveRoom",
            request_serializer=casino_dot_v1_dot_room__service__pb2.LeaveRoomRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_room__service__pb2.LeaveRoomResponse.FromString,
            _registered_method=True,
        )
        self.CloseRoom = channel.unary_unary(
            "/casino.v1.CasinoRoomService/CloseRoom",
            request_serializer=casino_dot_v1_dot_room__service__pb2.CloseRoomRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_room__service__pb2.CloseRoomResponse.FromString,
            _registered_method=True,
        )
        self.MarkParticipantDisconnected = channel.unary_unary(
            "/casino.v1.CasinoRoomService/MarkParticipantDisconnected",
            request_serializer=casino_dot_v1_dot_room__service__pb2.MarkParticipantDisconnectedRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_room__service__pb2.MarkParticipantDisconnectedResponse.FromString,
            _registered_method=True,
        )
        self.ResumeRoomSession = channel.unary_unary(
            "/casino.v1.CasinoRoomService/ResumeRoomSession",
            request_serializer=casino_dot_v1_dot_room__service__pb2.ResumeRoomSessionRequest.SerializeToString,
            response_deserializer=casino_dot_v1_dot_room__service__pb2.ResumeRoomSessionResponse.FromString,
            _registered_method=True,
        )


class CasinoRoomServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRoomSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def JoinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LeaveRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CloseRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MarkParticipantDisconnected(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResumeRoomSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CasinoRoomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateRoom": grpc.unary_unary_rpc_method_handler(
            servicer.CreateRoom,
            request_deserializer=casino_dot_v1_dot_room__service__pb2.CreateRoomRequest.FromString,
            response_serializer=casino_dot_v1_dot_room__service__pb2.CreateRoomResponse.SerializeToString,
        ),
        "ListRooms": grpc.unary_unary_rpc_method_handler(
            servicer.ListRooms,
            request_deserializer=casino_dot_v1_dot_room__service__pb2.ListRoomsRequest.FromString,
            response_serializer=casino_dot_v1_dot_room__service__pb2.ListRoomsResponse.SerializeToString,
        ),
        "GetRoomSnapshot": grpc.unary_unary_rpc_method_handler(
            servicer.GetRoomSnapshot,
            request_deserializer=casino_dot_v1_dot_room__service__pb2.GetRoomSnapshotRequest.FromString,
            response_serializer=casino_dot_v1_dot_room__service__pb2.GetRoomSnapshotResponse.SerializeToString,
        ),
        "JoinRoom": grpc.unary_unary_rpc_method_handler(
            servicer.JoinRoom,
            request_deserializer=casino_dot_v1_dot_room__service__pb2.JoinRoomRequest.FromString,
            response_serializer=casino_dot_v1_dot_room__service__pb2.JoinRoomResponse.SerializeToString,
        ),
        "LeaveRoom": grpc.unary_unary_rpc_method_handler(
            servicer.LeaveRoom,
            request_deserializer=casino_dot_v1_dot_room__service__pb2.LeaveRoomRequest.FromString,
            response_serializer=casino_dot_v1_dot_room__service__pb2.LeaveRoomResponse.SerializeToString,
        ),
        "CloseRoom": grpc.unary_unary_rpc_method_handler(
            servicer.CloseRoom,
            request_deserializer=casino_dot_v1_dot_room__service__pb2.CloseRoomRequest.FromString,
            response_serializer=casino_dot_v1_dot_room__service__pb2.CloseRoomResponse.SerializeToString,
        ),
        "MarkParticipantDisconnected": grpc.unary_unary_rpc_method_handler(
            servicer.MarkParticipantDisconnected,
            request_deserializer=casino_dot_v1_dot_room__service__pb2.MarkParticipantDisconnectedRequest.FromString,
            response_serializer=casino_dot_v1_dot_room__service__pb2.MarkParticipantDisconnectedResponse.SerializeToString,
        ),
        "ResumeRoomSession": grpc.unary_unary_rpc_method_handler(
            servicer.ResumeRoomSession,
            request_deserializer=casino_dot_v1_dot_room__service__pb2.ResumeRoomSessionRequest.FromString,
            response_serializer=casino_dot_v1_dot_room__service__pb2.ResumeRoomSessionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "casino.v1.CasinoRoomService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "casino.v1.CasinoRoomService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CasinoRoomService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRoom(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoRoomService/CreateRoom",
            casino_dot_v1_dot_room__service__pb2.CreateRoomRequest.SerializeToString,
            casino_dot_v1_dot_room__service__pb2.CreateRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListRooms(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoRoomService/ListRooms",
            casino_dot_v1_dot_room__service__pb2.ListRoomsRequest.SerializeToString,
            casino_dot_v1_dot_room__service__pb2.ListRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetRoomSnapshot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoRoomService/GetRoomSnapshot",
            casino_dot_v1_dot_room__service__pb2.GetRoomSnapshotRequest.SerializeToString,
            casino_dot_v1_dot_room__service__pb2.GetRoomSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def JoinRoom(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoRoomService/JoinRoom",
            casino_dot_v1_dot_room__service__pb2.JoinRoomRequest.SerializeToString,
            casino_dot_v1_dot_room__service__pb2.JoinRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LeaveRoom(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoRoomService/LeaveRoom",
            casino_dot_v1_dot_room__service__pb2.LeaveRoomRequest.SerializeToString,
            casino_dot_v1_dot_room__service__pb2.LeaveRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CloseRoom(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoRoomService/CloseRoom",
            casino_dot_v1_dot_room__service__pb2.CloseRoomRequest.SerializeToString,
            casino_dot_v1_dot_room__service__pb2.CloseRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MarkParticipantDisconnected(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoRoomService/MarkParticipantDisconnected",
            casino_dot_v1_dot_room__service__pb2.MarkParticipantDisconnectedRequest.SerializeToString,
            casino_dot_v1_dot_room__service__pb2.MarkParticipantDisconnectedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResumeRoomSession(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/casino.v1.CasinoRoomService/ResumeRoomSession",
            casino_dot_v1_dot_room__service__pb2.ResumeRoomSessionRequest.SerializeToString,
            casino_dot_v1_dot_room__service__pb2.ResumeRoomSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
