# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from casino.v1 import round_service_pb2 as casino_dot_v1_dot_round__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in casino/v1/round_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CasinoRoundServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRound = channel.unary_unary(
                '/casino.v1.CasinoRoundService/GetRound',
                request_serializer=casino_dot_v1_dot_round__service__pb2.GetRoundRequest.SerializeToString,
                response_deserializer=casino_dot_v1_dot_round__service__pb2.GetRoundResponse.FromString,
                _registered_method=True)
        self.GetCurrentRound = channel.unary_unary(
                '/casino.v1.CasinoRoundService/GetCurrentRound',
                request_serializer=casino_dot_v1_dot_round__service__pb2.GetCurrentRoundRequest.SerializeToString,
                response_deserializer=casino_dot_v1_dot_round__service__pb2.GetCurrentRoundResponse.FromString,
                _registered_method=True)
        self.ListRounds = channel.unary_unary(
                '/casino.v1.CasinoRoundService/ListRounds',
                request_serializer=casino_dot_v1_dot_round__service__pb2.ListRoundsRequest.SerializeToString,
                response_deserializer=casino_dot_v1_dot_round__service__pb2.ListRoundsResponse.FromString,
                _registered_method=True)
        self.SubmitRoundAction = channel.unary_unary(
                '/casino.v1.CasinoRoundService/SubmitRoundAction',
                request_serializer=casino_dot_v1_dot_round__service__pb2.SubmitRoundActionRequest.SerializeToString,
                response_deserializer=casino_dot_v1_dot_round__service__pb2.SubmitRoundActionResponse.FromString,
                _registered_method=True)


class CasinoRoundServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRounds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitRoundAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CasinoRoundServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRound': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRound,
                    request_deserializer=casino_dot_v1_dot_round__service__pb2.GetRoundRequest.FromString,
                    response_serializer=casino_dot_v1_dot_round__service__pb2.GetRoundResponse.SerializeToString,
            ),
            'GetCurrentRound': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentRound,
                    request_deserializer=casino_dot_v1_dot_round__service__pb2.GetCurrentRoundRequest.FromString,
                    response_serializer=casino_dot_v1_dot_round__service__pb2.GetCurrentRoundResponse.SerializeToString,
            ),
            'ListRounds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRounds,
                    request_deserializer=casino_dot_v1_dot_round__service__pb2.ListRoundsRequest.FromString,
                    response_serializer=casino_dot_v1_dot_round__service__pb2.ListRoundsResponse.SerializeToString,
            ),
            'SubmitRoundAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRoundAction,
                    request_deserializer=casino_dot_v1_dot_round__service__pb2.SubmitRoundActionRequest.FromString,
                    response_serializer=casino_dot_v1_dot_round__service__pb2.SubmitRoundActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'casino.v1.CasinoRoundService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('casino.v1.CasinoRoundService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CasinoRoundService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casino.v1.CasinoRoundService/GetRound',
            casino_dot_v1_dot_round__service__pb2.GetRoundRequest.SerializeToString,
            casino_dot_v1_dot_round__service__pb2.GetRoundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casino.v1.CasinoRoundService/GetCurrentRound',
            casino_dot_v1_dot_round__service__pb2.GetCurrentRoundRequest.SerializeToString,
            casino_dot_v1_dot_round__service__pb2.GetCurrentRoundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRounds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casino.v1.CasinoRoundService/ListRounds',
            casino_dot_v1_dot_round__service__pb2.ListRoundsRequest.SerializeToString,
            casino_dot_v1_dot_round__service__pb2.ListRoundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitRoundAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casino.v1.CasinoRoundService/SubmitRoundAction',
            casino_dot_v1_dot_round__service__pb2.SubmitRoundActionRequest.SerializeToString,
            casino_dot_v1_dot_round__service__pb2.SubmitRoundActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
